[package]
name = "Advent of Code 2015"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code 2015 puzzles"

[dependencies]

[[bin]]
name = "day01"

[[bin]]
name = "day02"

[[bin]]
name = "day03"
