[package]
name = "Advent of Code"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code puzzles. http://adventofcode.com/"

[dependencies]

[[bin]]
name = "day_01"
